version = "1.0"

[metadata]
author_name = "sankarganesh"
author_email = "sankarganesh232005@gmail.com"
difficulty = "easy"
category = "data-processing"
tags = ["text", "word-count"]
expert_time_estimate_min = 10.0
junior_time_estimate_min = 30.0

[verifier]
timeout_sec = 300

[agent]
timeout_sec = 1800

[environment]
build_timeout_sec = 300
cpus = 2
memory_mb = 4096
storage_mb = 10240
